{{- if .Values.backend.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: manhcaoduy191210/test:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - name: http
      port: 3000
      targetPort: 3000

{{- end }}
